Fixes 4 issues
techrail/bark-java-client pull request #16
Opened 2023-10-29 17:37 UTC by bhagatvansh

Fixes #2 , #3 , #4 , #5 

#2 and #3 done by me - disable debug logs and parse message function
#4 and #5 done by @theankitbhardwaj - adding stdout logger and support to add json to MoreData field

2023-11-05 17:01 UTC, theankitbhardwaj commented on src/main/java/bark/client/models/Config.java
> +    private Config(int serverMode, String baseUrl, String errorLevel, String serviceName, String serviceInstanceName, Logger logger, boolean bulkSend) {
serverMode should be removed

2023-11-05 17:03 UTC, theankitbhardwaj requested changes
Please remove mention of serverMode, otherwise LGTM.

2023-11-08 18:12 UTC, bhagatvansh commented
Server mode is needed to enable / disable sending to server.

2023-11-09 04:21 UTC, vaibhav-kaushal approved these changes

2023-11-09 04:21 UTC, merged